# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/fuzzlearn',
                'doc_host': 'https://ceshm.github.io',
                'git_url': 'https://github.com/ceshm/fuzzlearn',
                'lib_path': 'fuzzlearn'},
  'syms': {'fuzzlearn.core': {'fuzzlearn.core.foo': ('core.html#foo', 'fuzzlearn/core.py')}}}